const mainColors = {
  white: '#FFFFFF',
  green1: '#0BCAD4',
  green2: '#EDFCFD',
  grey3: '#EAEAEA',
  dark1: '#112340',
  dark2: '#495A75',
  dark3: '#8092AF',
  grey1: '#7D8797',
  grey2: '#E9E9E9',
  grey3: '#EDEEF0',
  grey4: '#646B86',
  grey4: '#B1B7C2',
  blue1: '#0000ff',
  blue2: '#66FFFF',
  blue3: '#6C6CFF',
  black1: '#000000',
  black2: 'rgba(0, 0, 0, 0.5)',
  red1: '#E06379',
  orange1: '#FF5216',
  yellow1: '#FEBB01',
  yellow2: '#ffe4c4',
};

export const colors = {
  primary: mainColors.blue1,
  secondary: mainColors.white,
  tertiary: mainColors.green1,
  white: 'white',
  black: 'black',
  grey: '#EAEBED',
  disable: mainColors.grey3,
  text: {
    primary: mainColors.dark1,
    secondary: mainColors.grey1,
    menuInactive: mainColors.dark1,
    menuActive: mainColors.blue3,
    subTittle: mainColors.dark3,
  },
  button: {
    primary: {
      background: mainColors.blue3,
      text: 'white',
    },
    secondary: {
      background: 'white',
      text: mainColors.dark1,
    },
    disable: {
      background: mainColors.grey3,
      text: mainColors.grey4,
    },
  },
  border: mainColors.grey2,
  cardLight: mainColors.green2,
  cardBlue: mainColors.blue3,
  loadingBackground: mainColors.black2,
  error: mainColors.red1,
};
